USE DB_rllantigua;


CREATE TABLE [dbo].[STG_WNBA_SEASON_STATS_2005_2017](
	[ID] [numeric](8 , 0)  NULL,
	[SEASON] [numeric](4 , 0) NOT NULL,
	[PLAYER] [varchar](255)  NULL,
	[TEAM] [varchar](100)  NULL,
	[AGE] [numeric](8, 0)  NULL,
	[GP] [numeric](8, 0)  NULL,
	[W] [numeric](8 , 0)  NULL,
	[L] [numeric](8 , 0)  NULL,
	[MIN] [numeric](8 , 0)  NULL,
	[PTS] [numeric](8 , 0)  NULL,
	[FGM] [numeric](8 , 0)  NULL,
	[FGA] [numeric](8 , 0)  NULL,
	[FG%] [numeric](8 , 3)  NULL,
	[_3PM] [numeric](8 , 0)  NULL,
	[_3PA] [numeric](8 , 0)  NULL,
	[_3P%] [numeric](8 , 3)  NULL,
	[FTM] [numeric](8 , 0)  NULL,
	[FTA] [numeric](8 , 0)  NULL,
	[FT%] [numeric](8 , 3)  NULL,
	[OREB] [numeric](8 , 0)  NULL,
	[DREB] [numeric](8 , 0)  NULL,
	[REB] [numeric](8 , 0)  NULL,
	[AST] [numeric](8 , 0)  NULL,
	[TOV] [numeric](8 , 0)  NULL,
	[STL] [numeric](8 , 0)  NULL,
	[BLK] [numeric](8 , 0)  NULL,
	[PF] [numeric](8 , 0)  NULL,
	[FP] [numeric](8 , 0)  NULL,
	[DD2] [numeric](8 , 0)  NULL,
	[TD3] [numeric](8 , 0)  NULL,
	[+/-] [numeric](8 , 0)  NULL,	
)
